### ISSUE TITLE
What is a `const` parameter and when a constant expression can reference a local variable?

### ISSUE THREAD

**Issue by pkulikov** [dotnet/csharpstandard#786] opened 2023-05-07 08:29 UTC
The [Constant expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1223-constant-expressions) section has the following entry:
![image](https://user-images.githubusercontent.com/15279990/236666287-fa1d866b-e065-4603-8224-19136fa582cf.png)

There are two questions to the highlighted list entry:

- What is "`const` parameter"?
- When can a constant expression reference a *local variable*?

For example, the following code results in a compiler error:

```csharp
const int a = 5;
const int b = a + 4;
int c = 4;
const int d = c + 1;  // Error CS0133 The expression being assigned to 'd' must be constant
```

Also, the list doesn't contain the item with references to local constants.

**Comment by Nigel-Ecma** [comment] 2023-05-09 00:58
@pkulikov – Well spotted!

This error arrived when an external document was merged into the Standard some years back and the errors were not spotted. There are two:

- As you spotted there are no `const` parameters!
- It refers to “`const` … local variables” (that is the way the language was intended to be parsed. In C# we don’t use the term ”constant variables” but rather “local constants”, e.g. as in the production *local-constant-declaration*.

If you’d like to make a PR and tag me as a reviewer please do, otherwise I’ll put a PR in myself.

(Note: C(++) documentation sometimes uses “constant variables” and does have constant parameters so that might explain how somebody wrote this in the first place – but that’s just me speculating!)

**Comment by pkulikov** [comment] 2023-05-09 18:05
@Nigel-Ecma thank you. Please check #789

**Closed as completed** 2023-05-09 18:12 UTC
