### ISSUE TITLE
Anonymous types equality and order of properties

### ISSUE THREAD

**Issue by jahbenjah** [dotnet/csharpstandard#266] opened 2020-05-21 14:37 UTC
two anonymous objects with the same Properties in different order should be equal ?

>The Equals and GetHashcode methods on anonymous types override the methods inherited from object, and are defined in terms of the Equals and GetHashcode of the properties, so that two instances of the same anonymous type are equal if and only if all their properties are equal.

```cs
var p1 = new { Name = "Lawnmower", Price = 495.00 };
var p2 = new { Name = "Lawnmower", Price = 495.00 };
var p3 = new { Price = 495.00, Name = "Lawnmower" };

Console.WriteLine($"are equal {p1.Equals(p2)}");// true
Console.WriteLine($"are equal {p1.Equals(p3)}"); //false
```
>Within the same program, two anonymous object initializers that specify a sequence of properties of the same names and compile-time types in the same order will produce instances of the same anonymous type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e783650c-e063-e268-316e-564362cb1e37
* Version Independent ID: aa9f4996-cab4-0bed-6452-213342453785
* Content: [Expressions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#anonymous-object-creation-expressions)
* Content Source: [spec/expressions.md](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-04-21 15:46
@jskeet 

This may be below the bar. The "in the same order" is already in informative text for assignment, but not for equality.

**Comment by jskeet** [comment] 2021-04-21 20:27
I think we probably do want to improve this, but I'm happy to close it as a duplicate of #114.

Labeling as "meeting:discuss" and "meeting:proposal" to ratify that decision.

**Comment by jskeet** [comment] 2024-09-12 09:15
Revisiting this many moons later - I still want to close this as a duplicate of #114. I'm re-adding "meeting: discuss" to make it easier to find in our meeting.

**Comment by jskeet** [comment] 2024-10-02 20:05
Closing as a duplicate.

**Closed by jskeet** 2024-10-02 20:05 UTC
Labels: type: clarity, meeting: discuss, meeting: proposal
